import type { FrontendModule } from '@/types'

export const modules: FrontendModule[] = [
  {
    name: 'command-room',
    label: 'Command Room',
    icon: 'CalendarClock',
    path: '/command-room',
    navGroup: 'primary',
    component: () => import('@modules/command-room/page'),
  },
  {
    name: 'fleet',
    label: 'Fleet',
    icon: 'BarChart3',
    path: '/fleet',
    navGroup: 'primary',
    component: () => import('@modules/fleet/page'),
  },
  {
    name: 'api-keys',
    label: 'Settings',
    icon: 'Settings',
    path: '/api-keys',
    navGroup: 'primary',
    component: () => import('@modules/api-keys/page'),
  },
  {
    name: 'telemetry',
    label: 'Telemetry Hub',
    icon: 'BarChart3',
    path: '/telemetry',
    navGroup: 'secondary',
    component: () => import('@modules/telemetry/page'),
  },
  {
    name: 'services',
    label: 'Services Manager',
    icon: 'Server',
    path: '/services',
    navGroup: 'secondary',
    component: () => import('@modules/services/page'),
  },
  {
    name: 'policies',
    label: 'Action Policies',
    icon: 'ShieldCheck',
    path: '/policies',
    navGroup: 'secondary',
    component: () => import('@modules/policies/page'),
  },
  {
    name: 'agents',
    label: 'Agents Monitor',
    icon: 'Monitor',
    path: '/agents',
    hideFromNav: true,
    component: () => import('@modules/hervald-redirect/page'),
  },
  {
    name: 'commanders',
    label: 'Commanders',
    icon: 'Crown',
    path: '/commanders',
    hideFromNav: true,
    component: () => import('@modules/hervald-redirect/page'),
  },
  {
    name: 'quests',
    label: 'Quests',
    icon: 'ClipboardCheck',
    path: '/quests',
    hideFromNav: true,
    component: () => import('@modules/hervald-redirect/page'),
  },
  {
    name: 'sentinels',
    label: 'Sentinels',
    icon: 'Clock3',
    path: '/sentinels',
    hideFromNav: true,
    component: () => import('@modules/hervald-redirect/page'),
  },
  {
    name: 'workspace',
    label: 'Workspace',
    icon: 'FolderOpen',
    path: '/workspace',
    hideFromNav: true,
    component: () => import('@modules/hervald-redirect/page'),
  },
  {
    name: 'rpg',
    label: 'RPG',
    icon: 'Swords',
    path: '/rpg',
    hideFromNav: true,
    component: () => import('@modules/rpg/page'),
  },
]
