import type { HammurabiModuleBrowserGraphMetadata } from './types/module-manifest.js'
import { COMMAND_ROOM_ROUTE_METADATA } from '../modules/command-room/route-metadata.js'

const emptyDependencies = {
  modules: [],
  capabilities: [],
} as const

const noUi = {
  kind: 'none',
  routes: [],
  componentKeys: [],
  surfaces: [],
} as const

export const HAMMURABI_MODULE_GRAPH = [
  {
    id: 'agents',
    label: 'Agents Monitor',
    directory: 'agents',
    status: 'public',
    summary: 'Agent session runtime, machine registry, stream events, and session WebSockets.',
    dependencies: {
      modules: ['policies', 'commanders'],
      capabilities: [
        'agents.provider-registry',
        'policies.action-gate',
        'commanders.data-dir',
        'commanders.store',
        'commanders.conversations',
        'commanders.session-seed-builder',
        'commanders.quest-store',
        'commanders.transcripts',
      ],
    },
    capabilities: {
      provides: [
        'agents.sessions',
        'agents.sessions-interface',
        'agents.approval-sessions-interface',
        'agents.session-websocket',
        'agents.runtime',
        'agents.machines',
        'agents.world-state',
        'agents.provider-registry',
      ],
      consumes: [
        'policies.action-gate',
        'commanders.data-dir',
        'commanders.store',
        'commanders.conversations',
        'commanders.session-seed-builder',
        'commanders.quest-store',
        'commanders.transcripts',
      ],
    },
    ui: {
      kind: 'embedded',
      routes: [],
      componentKeys: ['modules/agents/page', 'modules/agents/page-shell'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['agents.api', 'agents.providers-api'],
    parserIds: ['agents.image-json', 'agents.upload-multipart'],
    websocketIds: ['agents.session-stream', 'agents.daemon-channel'],
    storageKeys: ['agents.stream-sessions', 'agents.machines', 'agents.transcripts'],
  },
  {
    id: 'api-keys',
    label: 'Settings',
    directory: 'api-keys',
    status: 'public',
    summary: 'API key, transcription key, image-generation key, account, and provider secret settings surface.',
    dependencies: {
      modules: ['org-identity', 'operators'],
      capabilities: ['org-identity.profile', 'operators.founder-profile'],
    },
    capabilities: {
      provides: [
        'auth.api-keys',
        'api-key-store',
        'settings.provider-secrets',
        'provider-secrets-store',
        'realtime.transcription-key-store',
      ],
      consumes: ['org-identity.profile', 'operators.founder-profile'],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'api-keys.ui',
          path: '/api-keys',
          componentKey: 'modules/api-keys/page',
          surfaces: ['desktop', 'mobile'],
          nav: {
            label: 'Settings',
            icon: 'Settings',
            group: 'primary',
            surfaces: ['desktop'],
            order: 60,
          },
        },
      ],
      componentKeys: ['modules/api-keys/page'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['api-keys.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['api-keys.keys', 'api-keys.provider-secrets'],
  },
  {
    id: 'approvals',
    label: 'Approvals',
    directory: 'approvals',
    status: 'public',
    summary: 'Approval inbox, desktop Ops page, mobile sheet, and approval event stream surfaces.',
    dependencies: {
      modules: ['policies', 'agents'],
      capabilities: [
        'policies.approval-coordinator',
        'agents.approval-sessions-interface',
        'commanders.data-dir',
        'commanders.store',
      ],
    },
    capabilities: {
      provides: ['approvals.inbox-ui', 'approvals.pending-stream'],
      consumes: [
        'policies.approval-coordinator',
        'agents.approval-sessions-interface',
        'commanders.data-dir',
        'commanders.store',
      ],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'approvals.ui',
          path: '/approvals',
          componentKey: 'modules/approvals/page',
          surfaces: ['desktop'],
          nav: {
            label: 'Approvals',
            icon: 'ClipboardCheck',
            group: 'secondary',
            surfaces: ['desktop'],
            order: 40,
          },
        },
        {
          id: 'approvals.mobile-inbox-ui',
          path: '/command-room/inbox',
          componentKey: 'modules/approvals/MobileInbox',
          surfaces: ['mobile'],
          nav: {
            label: 'Inbox',
            icon: 'ClipboardCheck',
            group: 'primary',
            surfaces: ['mobile'],
            order: 30,
          },
        },
      ],
      componentKeys: ['modules/approvals/page', 'modules/approvals/MobileInbox'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['approvals.api'],
    parserIds: [],
    websocketIds: ['approvals.pending-stream'],
    storageKeys: ['approvals.pending', 'approvals.audit'],
  },
  {
    id: 'automations',
    label: 'Automations',
    directory: 'automations',
    status: 'public',
    summary: 'Automation definitions, executor, scheduler, run history, and command-room automation panels.',
    dependencies: {
      modules: ['agents', 'commanders'],
      capabilities: [
        'agents.sessions-interface',
        'commanders.store',
        'commanders.data-dir',
      ],
    },
    capabilities: {
      provides: [
        'automations.store',
        'automations.executor',
        'automations.scheduler',
        'automations.scheduler-initialized',
        'automations.quest-event-bus',
      ],
      consumes: [
        'agents.sessions-interface',
        'commanders.store',
        'commanders.data-dir',
      ],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'automations.ui',
          path: '/automations',
          componentKey: 'modules/automations/page',
          surfaces: ['desktop', 'mobile'],
          nav: {
            label: 'Automations',
            icon: 'CalendarClock',
            group: 'primary',
            surfaces: ['mobile'],
            order: 20,
          },
        },
      ],
      componentKeys: ['modules/automations/page', 'modules/automations/MobileAutomations'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['automations.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['automations.definitions', 'automations.runs', 'automations.memory'],
  },
  {
    id: 'channels',
    label: 'Channels',
    directory: 'channels',
    status: 'experimental',
    summary: 'Commander channel bindings, channel policy, resolver, email and WhatsApp adapter runtimes, and channel management page.',
    dependencies: {
      modules: ['commanders'],
      capabilities: ['commanders.store', 'commanders.data-dir'],
    },
    capabilities: {
      provides: ['channels.bindings', 'channels.resolver', 'channels.ingest'],
      consumes: ['commanders.store', 'commanders.data-dir'],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'channels.ui',
          path: '/channels',
          componentKey: 'modules/channels/page',
          surfaces: ['desktop'],
          nav: {
            label: 'Channels',
            icon: 'RadioTower',
            group: 'primary',
            order: 50,
          },
        },
      ],
      componentKeys: ['modules/channels/page'],
      surfaces: ['desktop'],
    },
    routeIds: ['channels.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['channels.bindings', 'channels.surface-bindings', 'channels.email-attachments', 'channels.whatsapp-auth'],
  },
  {
    id: 'command-room',
    label: 'Command Room',
    directory: 'command-room',
    status: 'public',
    summary: 'Desktop and mobile command-room shell that composes commanders, conversations, approvals, workspace, and automations.',
    dependencies: {
      modules: ['agents', 'approvals', 'automations', 'commanders', 'conversation', 'quests', 'settings', 'workspace'],
      capabilities: ['agents.sessions', 'commanders.store', 'commanders.conversations', 'approvals.inbox-ui', 'workspace.panel'],
    },
    capabilities: {
      provides: ['command-room.surface'],
      consumes: ['agents.sessions', 'commanders.store', 'commanders.conversations', 'workspace.panel'],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'command-room.ui',
          path: '/command-room',
          componentKey: 'modules/command-room/page',
          surfaces: ['desktop', 'mobile'],
          metadata: COMMAND_ROOM_ROUTE_METADATA,
          nav: {
            label: 'Command Room',
            icon: 'CalendarClock',
            group: 'primary',
            surfaces: ['desktop'],
            order: 20,
          },
        },
      ],
      redirects: [
        {
          id: 'command-room.legacy-automations-redirect',
          from: '/command-room/automations',
          toRouteId: 'automations.ui',
        },
      ],
      componentKeys: ['modules/command-room/page'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: [],
    parserIds: [],
    websocketIds: [],
    storageKeys: [],
  },
  {
    id: 'commanders',
    label: 'Commanders',
    directory: 'commanders',
    status: 'public',
    summary: 'Commander profiles, memory, conversations, quests, heartbeat, transcript, avatar, and runtime orchestration.',
    dependencies: {
      modules: ['agents', 'automations', 'channels', 'policies'],
      capabilities: [
        'agents.sessions-interface',
        'automations.scheduler',
        'automations.scheduler-initialized',
        'automations.quest-event-bus',
        'automations.store',
        'agents.session-websocket',
        'channels.bindings',
        'policies.action-gate',
        'provider-secrets-store',
      ],
    },
    capabilities: {
      provides: [
        'commanders.store',
        'commanders.conversations',
        'commanders.quest-store',
        'commanders.memory',
        'commanders.data-dir',
        'commanders.session-seed-builder',
        'commanders.runtime',
        'commanders.transcripts',
      ],
      consumes: [
        'agents.sessions-interface',
        'automations.scheduler',
        'automations.scheduler-initialized',
        'automations.quest-event-bus',
        'automations.store',
        'agents.session-websocket',
        'channels.bindings',
        'policies.action-gate',
        'provider-secrets-store',
      ],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'commanders.marketplace-ui',
          path: '/marketplace',
          componentKey: 'modules/commanders/packages/page',
          surfaces: ['desktop', 'mobile'],
          nav: {
            label: 'Marketplace',
            icon: 'Sparkles',
            group: 'primary',
            surfaces: ['desktop', 'mobile'],
            order: 30,
          },
        },
      ],
      componentKeys: [
        'modules/commanders/components',
        'modules/commanders/hooks',
        'modules/commanders/packages/page',
      ],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['commanders.api', 'commanders.packages-api', 'commanders.quests-api'],
    parserIds: ['commanders.avatar-multipart'],
    websocketIds: [],
    storageKeys: ['commanders.sessions', 'commanders.memory', 'commanders.quests', 'commanders.transcripts'],
  },
  {
    id: 'components',
    label: 'Shared Components',
    directory: 'components',
    status: 'embedded',
    summary: 'Shared module-owned UI primitives consumed by Hammurabi feature modules.',
    dependencies: emptyDependencies,
    capabilities: {
      provides: ['components.hervald-ui', 'components.modal-form'],
      consumes: [],
    },
    ui: {
      kind: 'embedded',
      routes: [],
      componentKeys: ['modules/components'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: [],
    parserIds: [],
    websocketIds: [],
    storageKeys: [],
  },
  {
    id: 'conversation',
    label: 'Conversations',
    directory: 'conversation',
    status: 'private',
    summary: 'Conversation hooks and components consumed by command-room and commander surfaces.',
    dependencies: {
      modules: ['commanders'],
      capabilities: ['commanders.conversations', 'commanders.runtime'],
    },
    capabilities: {
      provides: ['conversation.components', 'conversation.client-hooks'],
      consumes: ['commanders.conversations', 'commanders.runtime'],
    },
    ui: {
      kind: 'embedded',
      routes: [],
      componentKeys: ['modules/conversation/components', 'modules/conversation/hooks'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['conversation.api'],
    parserIds: ['conversation.image-json'],
    websocketIds: ['conversation.session-stream'],
    storageKeys: ['commanders.conversations'],
  },
  {
    id: 'onboarding',
    label: 'Welcome',
    directory: 'onboarding',
    status: 'public',
    summary: 'First-run founder, Gaia, provider, and machine onboarding flow shown before the main shell is available.',
    dependencies: {
      modules: ['agents', 'automations', 'commanders', 'operators', 'org', 'org-identity'],
      capabilities: [
        'agents.provider-registry',
        'automations.scheduler',
        'automations.scheduler-initialized',
        'automations.store',
        'commanders.data-dir',
        'commanders.store',
        'commanders.conversations',
        'org.setup',
        'operators.founder-profile',
        'operators.store',
      ],
    },
    capabilities: {
      provides: ['onboarding.founder-setup-ui', 'onboarding.status'],
      consumes: [
        'agents.provider-registry',
        'automations.scheduler',
        'automations.scheduler-initialized',
        'automations.store',
        'commanders.data-dir',
        'commanders.store',
        'commanders.conversations',
        'org.setup',
        'operators.founder-profile',
        'operators.store',
      ],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'onboarding.ui',
          path: '/welcome',
          componentKey: 'modules/onboarding/page',
          surfaces: ['desktop', 'mobile'],
          nav: {
            label: 'Welcome',
            icon: 'Sparkles',
            group: 'primary',
            hidden: true,
          },
        },
      ],
      componentKeys: ['modules/onboarding/page'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['onboarding.api'],
    parserIds: ['onboarding.json'],
    websocketIds: [],
    storageKeys: [],
  },
  {
    id: 'operators',
    label: 'Operators',
    directory: 'operators',
    status: 'private',
    summary: 'Operator and founder profile API, avatar storage, and bootstrap profile helpers.',
    dependencies: {
      modules: ['org-identity'],
      capabilities: ['auth.user'],
    },
    capabilities: {
      provides: ['operators.store', 'operators.founder-profile'],
      consumes: ['auth.user'],
    },
    ui: {
      kind: 'embedded',
      routes: [],
      componentKeys: ['modules/operators/hooks'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['operators.api'],
    parserIds: ['operators.avatar-multipart'],
    websocketIds: [],
    storageKeys: ['operators.profiles', 'operators.avatars'],
  },
  {
    id: 'org',
    label: 'Org',
    directory: 'org',
    status: 'public',
    summary: 'Organization read model, commander management panels, operator cards, and founder setup writes.',
    dependencies: {
      modules: ['automations', 'commanders', 'operators', 'org-identity'],
      capabilities: [
        'automations.store',
        'commanders.data-dir',
        'commanders.store',
        'commanders.conversations',
        'commanders.quest-store',
        'operators.store',
        'org-identity.store',
      ],
    },
    capabilities: {
      provides: ['org.read-model', 'org.setup'],
      consumes: [
        'automations.store',
        'commanders.data-dir',
        'commanders.store',
        'commanders.conversations',
        'commanders.quest-store',
        'operators.store',
      ],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'org.ui',
          path: '/org',
          componentKey: 'modules/org/page',
          surfaces: ['desktop', 'mobile'],
          nav: {
            label: 'Org',
            icon: 'Users',
            group: 'primary',
            surfaces: ['desktop', 'mobile'],
            order: 10,
          },
        },
      ],
      componentKeys: ['modules/org/page'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['org.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['org.identity', 'operators.profiles', 'commanders.sessions'],
  },
  {
    id: 'org-identity',
    label: 'Org Identity',
    directory: 'org-identity',
    status: 'private',
    summary: 'Organization identity card, identity API, and persisted org profile data.',
    dependencies: {
      modules: ['operators'],
      capabilities: ['auth.user'],
    },
    capabilities: {
      provides: ['org-identity.store', 'org-identity.profile'],
      consumes: ['auth.user'],
    },
    ui: {
      kind: 'embedded',
      routes: [],
      componentKeys: ['modules/org-identity/components'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['org-identity.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['org.identity'],
  },
  {
    id: 'policies',
    label: 'Action Policies',
    directory: 'policies',
    status: 'public',
    summary: 'Action-policy API, built-in action registry, policy store, action gate, and approval coordination.',
    dependencies: {
      modules: ['agents'],
      capabilities: ['agents.approval-sessions-interface'],
    },
    capabilities: {
      provides: ['policies.store', 'policies.action-gate', 'policies.approval-coordinator'],
      consumes: ['agents.approval-sessions-interface'],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'policies.ui',
          path: '/policies',
          componentKey: 'modules/policies/page',
          surfaces: ['desktop'],
          nav: {
            label: 'Policies',
            icon: 'ShieldCheck',
            group: 'secondary',
            surfaces: ['desktop'],
            order: 42,
          },
        },
      ],
      componentKeys: ['modules/policies/page'],
      surfaces: ['desktop'],
    },
    routeIds: ['policies.api', 'approval-check.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['policies.rules', 'approvals.pending', 'approvals.audit'],
  },
  {
    id: 'quests',
    label: 'Quests',
    directory: 'quests',
    status: 'private',
    summary: 'Quest board UI and commander quest store surfaces embedded in command-room.',
    dependencies: {
      modules: ['commanders'],
      capabilities: ['commanders.quest-store'],
    },
    capabilities: {
      provides: ['quests.board-ui'],
      consumes: ['commanders.quest-store'],
    },
    ui: {
      kind: 'embedded',
      routes: [],
      componentKeys: ['modules/quests/page', 'modules/commanders/components/QuestBoard'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: [],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['commanders.quests'],
  },
  {
    id: 'rpg',
    label: 'RPG',
    directory: 'rpg',
    status: 'experimental',
    summary: 'Experimental RPG visualization for world state, agents, and command interactions.',
    dependencies: {
      modules: ['agents', 'commanders'],
      capabilities: ['agents.world-state', 'agents.session-websocket'],
    },
    capabilities: {
      provides: ['rpg.visualization-ui'],
      consumes: ['agents.world-state', 'agents.session-websocket'],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'rpg.ui',
          path: '/rpg',
          componentKey: 'modules/rpg/page',
          surfaces: ['desktop'],
          nav: {
            label: 'RPG',
            icon: 'Swords',
            group: 'primary',
            hidden: true,
          },
        },
      ],
      componentKeys: ['modules/rpg/page'],
      surfaces: ['desktop'],
    },
    routeIds: [],
    parserIds: [],
    websocketIds: [],
    storageKeys: [],
  },
  {
    id: 'sentinels',
    label: 'Sentinels',
    directory: 'sentinels',
    status: 'retired',
    summary: 'Legacy sentinel scheduler, executor, store, and routes retained for explicit retirement or future reactivation.',
    dependencies: {
      modules: ['agents', 'commanders'],
      capabilities: ['agents.sessions-interface'],
    },
    capabilities: {
      provides: ['sentinels.legacy-store', 'sentinels.legacy-scheduler'],
      consumes: ['agents.sessions-interface'],
    },
    ui: {
      kind: 'embedded',
      routes: [],
      componentKeys: ['modules/sentinels/page'],
      surfaces: ['desktop'],
    },
    routeIds: ['sentinels.legacy-api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['sentinels.legacy'],
  },
  {
    id: 'settings',
    label: 'App Settings',
    directory: 'settings',
    status: 'private',
    summary: 'Application settings API, theme persistence, and mobile settings panels embedded by command-room.',
    dependencies: {
      modules: ['api-keys'],
      capabilities: ['auth.api-keys'],
    },
    capabilities: {
      provides: ['settings.app-settings', 'settings.mobile-ui'],
      consumes: ['auth.api-keys'],
    },
    ui: {
      kind: 'embedded',
      routes: [
        {
          id: 'settings.mobile-ui',
          path: '/command-room/settings',
          componentKey: 'modules/settings/MobileSettings',
          surfaces: ['mobile'],
          nav: {
            label: 'Settings',
            icon: 'Settings',
            group: 'primary',
            surfaces: ['mobile'],
            order: 40,
          },
        },
      ],
      componentKeys: ['modules/settings/MobileSettings'],
      surfaces: ['mobile'],
    },
    routeIds: ['settings.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['settings.app'],
  },
  {
    id: 'skills',
    label: 'Skills Discovery',
    directory: 'skills',
    status: 'experimental',
    summary: 'Installed skill discovery API consumed by composer, automations, sentinels, and policies.',
    dependencies: emptyDependencies,
    capabilities: {
      provides: ['skills.discovery'],
      consumes: [],
    },
    ui: noUi,
    routeIds: ['skills.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: [],
  },
  {
    id: 'telemetry',
    label: 'Telemetry Hub',
    directory: 'telemetry',
    status: 'public',
    summary: 'Telemetry hub, OTEL receiver, local scanner, telemetry store, summaries, and telemetry dashboard.',
    dependencies: {
      modules: ['api-keys'],
      capabilities: ['auth.api-keys'],
    },
    capabilities: {
      provides: ['telemetry.hub', 'telemetry.store', 'telemetry.otel-receiver'],
      consumes: ['auth.api-keys'],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'telemetry.ui',
          path: '/telemetry',
          componentKey: 'modules/telemetry/page',
          surfaces: ['desktop'],
          nav: {
            label: 'Telemetry',
            icon: 'BarChart3',
            group: 'secondary',
            surfaces: ['desktop'],
            order: 41,
          },
        },
      ],
      componentKeys: ['modules/telemetry/page'],
      surfaces: ['desktop'],
    },
    routeIds: ['telemetry.api', 'telemetry.otel-api'],
    parserIds: ['telemetry.otel-json'],
    websocketIds: [],
    storageKeys: ['telemetry.events'],
  },
  {
    id: 'workspace',
    label: 'Workspace',
    directory: 'workspace',
    status: 'private',
    summary: 'Target-based workspace tree, file preview, raw file, git reads, and workspace preferences.',
    dependencies: {
      modules: ['agents', 'commanders'],
      capabilities: ['agents.sessions-interface', 'commanders.conversations', 'commanders.store'],
    },
    capabilities: {
      provides: ['workspace.machineDescriptor', 'workspace.panel', 'workspace.resolver'],
      consumes: ['agents.sessions-interface', 'commanders.conversations', 'commanders.store'],
    },
    ui: {
      kind: 'embedded',
      routes: [],
      componentKeys: ['modules/workspace/components', 'modules/workspace/use-workspace'],
      surfaces: ['desktop', 'mobile'],
    },
    routeIds: ['workspace.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['workspace.conversation-targets', 'workspace.preferences'],
  },
  {
    id: 'module-graph',
    label: 'Module Graph',
    directory: 'module-graph',
    status: 'private',
    summary: 'Authenticated backend graph endpoint for enabled modules, routes, navigation metadata, providers, and capabilities.',
    dependencies: {
      modules: ['agents'],
      capabilities: ['agents.provider-registry'],
    },
    capabilities: {
      provides: ['module-graph.read-model'],
      consumes: ['agents.provider-registry'],
    },
    ui: noUi,
    routeIds: ['module-graph.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: [],
  },
  {
    id: 'realtime',
    label: 'Realtime Transcription',
    directory: 'realtime',
    status: 'private',
    summary: 'Realtime browser-to-provider transcription proxy and websocket bridge.',
    dependencies: {
      modules: ['api-keys'],
      capabilities: ['realtime.transcription-key-store'],
    },
    capabilities: {
      provides: ['realtime.transcription-websocket'],
      consumes: ['realtime.transcription-key-store'],
    },
    ui: noUi,
    routeIds: ['realtime.api'],
    parserIds: [],
    websocketIds: ['realtime.transcription'],
    storageKeys: [],
  },
  {
    id: 'eval',
    label: 'Eval',
    directory: 'eval',
    status: 'private',
    summary: 'Internal benchmark evaluation runner manifests, auth doctor, result reports, and submission state.',
    dependencies: {
      modules: ['api-keys', 'telemetry'],
      capabilities: ['auth.api-keys', 'telemetry.hub'],
    },
    capabilities: {
      provides: ['eval.result-manifests', 'eval.auth-doctor', 'eval.reports-ui'],
      consumes: ['auth.api-keys', 'telemetry.hub'],
    },
    ui: {
      kind: 'route',
      routes: [
        {
          id: 'eval.ui',
          path: '/eval',
          componentKey: 'modules/eval/page',
          surfaces: ['desktop'],
          nav: {
            label: 'Eval',
            icon: 'Gauge',
            group: 'secondary',
            surfaces: ['desktop'],
            order: 110,
          },
        },
      ],
      componentKeys: ['modules/eval/page'],
      surfaces: ['desktop'],
    },
    routeIds: ['eval.api'],
    parserIds: [],
    websocketIds: [],
    storageKeys: ['eval.result-manifests'],
  },
] as const satisfies readonly HammurabiModuleBrowserGraphMetadata[]
