import type { FrontendModule } from '@/types'

export const modules: FrontendModule[] = [
  {
    name: 'org',
    label: 'Org',
    icon: 'Users',
    path: '/org',
    navGroup: 'primary',
    component: () => import('@modules/org/page'),
  },
  {
    name: 'command-room',
    label: 'Command Room',
    icon: 'CalendarClock',
    path: '/command-room',
    navGroup: 'primary',
    component: () => import('@modules/command-room/page'),
  },
  {
    name: 'api-keys',
    label: 'Settings',
    icon: 'Settings',
    path: '/api-keys',
    navGroup: 'primary',
    component: () => import('@modules/api-keys/page'),
  },
  {
    name: 'channels',
    label: 'Channels',
    icon: 'RadioTower',
    path: '/channels',
    hideFromNav: true,
    component: () => import('@modules/channels/page'),
  },
  {
    name: 'telemetry',
    label: 'Telemetry Hub',
    icon: 'BarChart3',
    path: '/telemetry',
    navGroup: 'secondary',
    component: () => import('@modules/telemetry/page'),
  },
  {
    name: 'services',
    label: 'Services Manager',
    icon: 'Server',
    path: '/services',
    navGroup: 'secondary',
    component: () => import('@modules/services/page'),
  },
  {
    name: 'policies',
    label: 'Action Policies',
    icon: 'ShieldCheck',
    path: '/policies',
    navGroup: 'secondary',
    component: () => import('@modules/policies/page'),
  },
  {
    name: 'rpg',
    label: 'RPG',
    icon: 'Swords',
    path: '/rpg',
    hideFromNav: true,
    component: () => import('@modules/rpg/page'),
  },
]
