import { existsSync } from 'node:fs'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { buildClaudeCodeOtelEnv, mergeClaudeCodeEnv } from './claude-settings.js'
import { buildCodexOtelConfig, mergeCodexOtelConfig } from './codex-settings.js'
import {
  createHammurabiConfig,
  defaultConfigPath,
  type HammurabiAgent,
  writeHammurabiConfig,
} from './config.js'
import { buildCursorOtelEnv, mergeCursorEnv } from './cursor-settings.js'
import {
  closePromptResources,
  promptMultiSelect,
  promptText,
  type MultiSelectOption,
} from './prompts.js'
import {
  DEFAULT_HAMBROS_LOCAL_ORIGIN,
  resolveHambrosAppRoot,
  resolveHambrosEnvPath,
  resolveHambrosHome,
} from './local-install.js'

interface Writable {
  write(chunk: string): boolean
}

interface InitCliDependencies {
  env?: NodeJS.ProcessEnv
  fileExists?: (path: string) => boolean
  mkdirImpl?: typeof mkdir
  readFileImpl?: typeof readFile
  writeFileImpl?: typeof writeFile
  promptTextImpl?: typeof promptText
  promptMultiSelectImpl?: typeof promptMultiSelect
  writeConfig?: typeof writeHammurabiConfig
  mergeClaudeCodeEnvImpl?: typeof mergeClaudeCodeEnv
  mergeCodexOtelConfigImpl?: typeof mergeCodexOtelConfig
  mergeCursorEnvImpl?: typeof mergeCursorEnv
  stdout?: Writable
  stderr?: Writable
}

const INIT_AGENT_OPTIONS: readonly MultiSelectOption<HammurabiAgent>[] = [
  { value: 'claude-code', label: 'Claude Code' },
  { value: 'codex', label: 'Codex' },
  { value: 'cursor', label: 'Cursor' },
] as const

const DEFAULT_INIT_AGENTS: readonly HammurabiAgent[] = [
  'claude-code',
  'codex',
  'cursor',
]

const ENV_LINE_PATTERN = /^\s*([A-Z0-9_]+)=(.*)$/u

function printUsage(stdout: Writable): void {
  stdout.write('Usage: hambros init\n')
}

function parseEnvAssignments(raw: string): Map<string, string> {
  const assignments = new Map<string, string>()

  for (const line of raw.split(/\r?\n/u)) {
    const match = line.match(ENV_LINE_PATTERN)
    if (!match) {
      continue
    }

    assignments.set(match[1], match[2])
  }

  return assignments
}

function renderEnvFile(
  existingRaw: string,
  updates: Record<string, string>,
): string {
  if (existingRaw.trim().length === 0) {
    return [
      '# Generated by `hambros init`.',
      `PORT=${updates.PORT}`,
      `HAMBROS_ALLOWED_ORIGINS=${updates.HAMBROS_ALLOWED_ORIGINS}`,
      `HAMBROS_DEFAULT_KEY=${updates.HAMBROS_DEFAULT_KEY}`,
      '',
    ].join('\n')
  }

  const seen = new Set<string>()
  const lines = existingRaw.split(/\r?\n/u)
  const nextLines = lines.map((line) => {
    const match = line.match(ENV_LINE_PATTERN)
    if (!match) {
      return line
    }

    const key = match[1]
    if (!(key in updates)) {
      return line
    }

    seen.add(key)
    return `${key}=${updates[key]}`
  })

  for (const [key, value] of Object.entries(updates)) {
    if (!seen.has(key)) {
      nextLines.push(`${key}=${value}`)
    }
  }

  while (nextLines.length > 0 && nextLines[nextLines.length - 1] === '') {
    nextLines.pop()
  }

  return `${nextLines.join('\n')}\n`
}

function normalizePort(value: string): string | null {
  const trimmed = value.trim()
  if (!/^\d+$/u.test(trimmed)) {
    return null
  }

  const parsed = Number.parseInt(trimmed, 10)
  if (!Number.isFinite(parsed) || parsed < 1 || parsed > 65_535) {
    return null
  }

  return String(parsed)
}

async function promptForPort(
  promptTextImpl: typeof promptText,
  defaultValue: string,
  stderr: Writable,
): Promise<string> {
  while (true) {
    const response = await promptTextImpl('Server port', {
      defaultValue,
      required: true,
    })

    const normalized = normalizePort(response)
    if (normalized) {
      return normalized
    }

    stderr.write('Server port must be a number between 1 and 65535.\n')
  }
}

async function autoConfigureAgents(
  endpoint: string,
  apiKey: string,
  agents: readonly HammurabiAgent[],
  deps: Required<Pick<
    InitCliDependencies,
    'mergeClaudeCodeEnvImpl' | 'mergeCodexOtelConfigImpl' | 'mergeCursorEnvImpl'
  >>,
  stderr: Writable,
): Promise<readonly HammurabiAgent[]> {
  const configured: HammurabiAgent[] = []

  if (agents.includes('claude-code')) {
    try {
      await deps.mergeClaudeCodeEnvImpl(buildClaudeCodeOtelEnv(endpoint, apiKey))
      configured.push('claude-code')
    } catch {
      stderr.write('Claude Code auto-configuration failed. Configure it manually if needed.\n')
    }
  }

  if (agents.includes('codex')) {
    try {
      await deps.mergeCodexOtelConfigImpl(buildCodexOtelConfig(endpoint, apiKey))
      configured.push('codex')
    } catch {
      stderr.write('Codex auto-configuration failed. Configure it manually if needed.\n')
    }
  }

  if (agents.includes('cursor')) {
    try {
      await deps.mergeCursorEnvImpl(buildCursorOtelEnv(endpoint, apiKey))
      configured.push('cursor')
    } catch {
      stderr.write('Cursor auto-configuration failed. Configure it manually if needed.\n')
    }
  }

  return configured
}

export async function runInitCli(
  args: readonly string[],
  dependencies: InitCliDependencies = {},
): Promise<number> {
  const env = dependencies.env ?? process.env
  const fileExists = dependencies.fileExists ?? existsSync
  const mkdirImpl = dependencies.mkdirImpl ?? mkdir
  const readFileImpl = dependencies.readFileImpl ?? readFile
  const writeFileImpl = dependencies.writeFileImpl ?? writeFile
  const promptTextImpl = dependencies.promptTextImpl ?? promptText
  const promptMultiSelectImpl = dependencies.promptMultiSelectImpl ?? promptMultiSelect
  const writeConfig = dependencies.writeConfig ?? writeHammurabiConfig
  const mergeClaudeCodeEnvImpl = dependencies.mergeClaudeCodeEnvImpl ?? mergeClaudeCodeEnv
  const mergeCodexOtelConfigImpl = dependencies.mergeCodexOtelConfigImpl ?? mergeCodexOtelConfig
  const mergeCursorEnvImpl = dependencies.mergeCursorEnvImpl ?? mergeCursorEnv
  const stdout = dependencies.stdout ?? process.stdout
  const stderr = dependencies.stderr ?? process.stderr

  try {
    if (args.length > 0) {
      printUsage(stdout)
      return 1
    }

    const hambrosHome = resolveHambrosHome(env)
    const appRoot = resolveHambrosAppRoot(env)
    const envPath = resolveHambrosEnvPath(env)
    const appPackagePath = path.join(appRoot, 'package.json')

    if (!fileExists(appPackagePath)) {
      stderr.write(`HamBros install not found at ${hambrosHome}. Run install.sh first.\n`)
      return 1
    }

    let existingEnvRaw = ''
    try {
      existingEnvRaw = await readFileImpl(envPath, 'utf8')
    } catch {
      existingEnvRaw = ''
    }

    const existingValues = parseEnvAssignments(existingEnvRaw)
    stdout.write(
      existingEnvRaw.trim().length > 0
        ? `Existing install detected at ${hambrosHome}.\n`
        : `Fresh install detected at ${hambrosHome}.\n`,
    )

    const port = await promptForPort(
      promptTextImpl,
      existingValues.get('PORT') ?? '20001',
      stderr,
    )
    const apiKey = await promptTextImpl('Admin API key', {
      defaultValue: existingValues.get('HAMBROS_DEFAULT_KEY') ?? 'HAMBROS!',
      required: true,
    })
    const agents = await promptMultiSelectImpl<HammurabiAgent>(
      'Agents to instrument:',
      INIT_AGENT_OPTIONS,
      DEFAULT_INIT_AGENTS,
    )

    const endpoint = `http://localhost:${port}`
    const envContents = renderEnvFile(existingEnvRaw, {
      PORT: port,
      HAMBROS_ALLOWED_ORIGINS:
        existingValues.get('HAMBROS_ALLOWED_ORIGINS') ?? DEFAULT_HAMBROS_LOCAL_ORIGIN,
      HAMBROS_DEFAULT_KEY: apiKey.trim(),
    })

    await mkdirImpl(path.dirname(envPath), { recursive: true })
    await writeFileImpl(envPath, envContents, 'utf8')

    const config = createHammurabiConfig({
      endpoint,
      apiKey,
      agents,
    })
    await writeConfig(config)

    const autoConfigured = await autoConfigureAgents(
      endpoint,
      apiKey,
      agents,
      {
        mergeClaudeCodeEnvImpl,
        mergeCodexOtelConfigImpl,
        mergeCursorEnvImpl,
      },
      stderr,
    )

    stdout.write(`Saved app env: ${envPath}\n`)
    stdout.write(`Saved CLI config: ${defaultConfigPath()}\n`)
    if (autoConfigured.length > 0) {
      stdout.write(`Auto-configured agents: ${autoConfigured.join(', ')}\n`)
    }
    stdout.write("Run 'hambros start' to launch your instance.\n")
    return 0
  } finally {
    closePromptResources()
  }
}
