import type {
  ChannelDescriptorField,
  ChannelProviderDescriptor,
  ChannelProvider,
  ChannelCommanderBindingState,
  CommanderChannelBinding,
} from './types.js'

const PROVIDER_LABELS: Readonly<Record<string, string>> = {
  email: 'Email',
  whatsapp: 'WhatsApp',
  googlechat: 'Google Chat',
  telegram: 'Telegram',
  discord: 'Discord',
}

const POLICY_OPTIONS = [
  { value: 'allowlist', label: 'Allowlist' },
  { value: 'open', label: 'Open' },
  { value: 'disabled', label: 'Disabled' },
]

const COMMANDER_BINDING = {
  mode: 'account-commander',
  fieldKey: 'defaultCommanderId',
  label: 'Default Commander',
  source: 'bindingState.defaultCommanderId',
  emptyLabel: 'None',
} as const

const EMAIL_FIELDS: readonly ChannelDescriptorField[] = [
  {
    key: 'accountId',
    formKey: 'accountId',
    label: 'Mailbox',
    kind: 'text',
    required: true,
    placeholder: 'assistant@example.com',
    section: 'identity',
  },
  {
    key: 'displayName',
    formKey: 'displayName',
    label: 'Display Name',
    kind: 'text',
    required: true,
    placeholder: 'Team Email',
    section: 'identity',
  },
  {
    key: 'appPassword',
    formKey: 'appPassword',
    label: 'App Password',
    kind: 'password',
    required: true,
    secret: true,
    placeholder: 'stored encrypted',
    section: 'credentials',
  },
  {
    key: 'username',
    formKey: 'username',
    configPath: 'username',
    label: 'Username',
    kind: 'text',
    placeholder: 'assistant@example.com',
    section: 'account',
  },
  {
    key: 'fromAddress',
    formKey: 'fromAddress',
    configPath: 'fromAddress',
    label: 'From',
    kind: 'text',
    placeholder: 'assistant@example.com',
    section: 'account',
  },
  {
    key: 'replyFromAddress',
    formKey: 'replyFromAddress',
    configPath: 'replyFromAddress',
    label: 'Reply From',
    kind: 'text',
    placeholder: 'assistant@example.com',
    section: 'account',
  },
  {
    key: 'emailAlias',
    formKey: 'emailAlias',
    configPath: 'emailAlias',
    label: 'Plus Alias',
    kind: 'text',
    placeholder: 'atlas',
    section: 'account',
  },
  {
    key: 'defaultCommanderId',
    formKey: 'defaultCommanderId',
    label: 'Default Commander',
    kind: 'select',
    section: 'binding',
  },
  {
    key: 'imapHost',
    formKey: 'imapHost',
    configPath: 'imapHost',
    label: 'IMAP Host',
    kind: 'text',
    required: true,
    defaultValue: 'imap.gmail.com',
    section: 'imap',
  },
  {
    key: 'imapPort',
    formKey: 'imapPort',
    configPath: 'imapPort',
    label: 'IMAP Port',
    kind: 'number',
    required: true,
    defaultValue: '993',
    section: 'imap',
  },
  {
    key: 'imapMailbox',
    formKey: 'imapMailbox',
    configPath: 'imapMailbox',
    label: 'IMAP Mailbox',
    kind: 'text',
    required: true,
    defaultValue: 'INBOX',
    section: 'imap',
  },
  {
    key: 'smtpHost',
    formKey: 'smtpHost',
    configPath: 'smtpHost',
    label: 'SMTP Host',
    kind: 'text',
    required: true,
    defaultValue: 'smtp.gmail.com',
    section: 'smtp',
  },
  {
    key: 'smtpPort',
    formKey: 'smtpPort',
    configPath: 'smtpPort',
    label: 'SMTP Port',
    kind: 'number',
    required: true,
    defaultValue: '465',
    section: 'smtp',
  },
  {
    key: 'pollIntervalSeconds',
    formKey: 'pollIntervalSeconds',
    configPath: 'pollIntervalMs',
    label: 'Poll Seconds',
    kind: 'number',
    required: true,
    min: 5,
    defaultValue: '15',
    section: 'imap',
  },
  {
    key: 'imapSecure',
    formKey: 'imapSecure',
    configPath: 'imapSecure',
    label: 'IMAP TLS',
    kind: 'checkbox',
    defaultValue: true,
    section: 'imap',
  },
  {
    key: 'smtpSecure',
    formKey: 'smtpSecure',
    configPath: 'smtpSecure',
    label: 'SMTP TLS',
    kind: 'checkbox',
    defaultValue: true,
    section: 'smtp',
  },
  {
    key: 'allowlist',
    formKey: 'allowlist',
    configPath: 'allowlist',
    label: 'Allowed Senders',
    kind: 'textarea',
    placeholder: 'nick@example.com',
    section: 'policy',
  },
  {
    key: 'globalAllowlist',
    formKey: 'globalAllowlist',
    configPath: 'globalAllowlist',
    label: 'Global Allowlist',
    kind: 'textarea',
    placeholder: 'founder@example.com',
    section: 'policy',
  },
]

const WHATSAPP_FIELDS: readonly ChannelDescriptorField[] = [
  {
    key: 'accountId',
    formKey: 'accountId',
    label: 'Account ID',
    kind: 'text',
    placeholder: 'optional; generated if blank',
    section: 'identity',
  },
  {
    key: 'displayName',
    formKey: 'displayName',
    label: 'Display Name',
    kind: 'text',
    required: true,
    placeholder: "Nick's WhatsApp",
    section: 'identity',
  },
  {
    key: 'transport',
    formKey: 'transport',
    configPath: 'transport',
    label: 'Transport',
    kind: 'static',
    readonly: true,
    defaultValue: 'baileys',
    section: 'transport',
    options: [{ value: 'baileys', label: 'Baileys QR' }],
  },
  {
    key: 'browserName',
    formKey: 'browserName',
    configPath: 'baileys.browserName',
    label: 'Baileys Browser',
    kind: 'text',
    placeholder: 'Hervald',
    defaultValue: 'Hervald',
    section: 'transport',
  },
  {
    key: 'authStateDir',
    formKey: 'authStateDir',
    configPath: 'baileys.authStateDir',
    label: 'Auth State Dir',
    kind: 'text',
    placeholder: 'default under ~/.hammurabi',
    section: 'transport',
  },
  {
    key: 'connectTimeoutSeconds',
    formKey: 'connectTimeoutSeconds',
    configPath: 'baileys.connectTimeoutMs',
    label: 'QR Timeout Seconds',
    kind: 'number',
    required: true,
    min: 1,
    defaultValue: '30',
    section: 'transport',
  },
  {
    key: 'printQrInTerminal',
    formKey: 'printQrInTerminal',
    configPath: 'baileys.printQrInTerminal',
    label: 'Terminal QR',
    kind: 'checkbox',
    defaultValue: true,
    section: 'transport',
  },
  {
    key: 'reconnect',
    formKey: 'reconnect',
    configPath: 'baileys.reconnect',
    label: 'Reconnect',
    kind: 'checkbox',
    defaultValue: true,
    section: 'transport',
  },
  {
    key: 'markOnlineOnConnect',
    formKey: 'markOnlineOnConnect',
    configPath: 'baileys.markOnlineOnConnect',
    label: 'Mark Online',
    kind: 'checkbox',
    defaultValue: false,
    section: 'transport',
  },
  {
    key: 'syncFullHistory',
    formKey: 'syncFullHistory',
    configPath: 'baileys.syncFullHistory',
    label: 'Sync Full History',
    kind: 'checkbox',
    defaultValue: false,
    section: 'transport',
  },
  {
    key: 'sendTextWithVoiceNote',
    formKey: 'sendTextWithVoiceNote',
    configPath: 'baileys.sendTextWithVoiceNote',
    label: 'Text With Voice',
    kind: 'checkbox',
    defaultValue: false,
    section: 'transport',
  },
  {
    key: 'dmPolicy',
    formKey: 'dmPolicy',
    configPath: 'dmPolicy',
    label: 'DM Policy',
    kind: 'select',
    defaultValue: 'allowlist',
    section: 'policy',
    options: POLICY_OPTIONS,
  },
  {
    key: 'groupPolicy',
    formKey: 'groupPolicy',
    configPath: 'groupPolicy',
    label: 'Group Policy',
    kind: 'select',
    defaultValue: 'disabled',
    section: 'policy',
    options: POLICY_OPTIONS,
  },
  {
    key: 'ttsVoice',
    formKey: 'ttsVoice',
    configPath: 'tts.voice',
    label: 'TTS Voice',
    kind: 'text',
    placeholder: 'alloy',
    defaultValue: 'alloy',
    section: 'voice',
  },
  {
    key: 'ttsEnabled',
    formKey: 'ttsEnabled',
    configPath: 'tts.enabled',
    label: 'TTS',
    kind: 'checkbox',
    defaultValue: false,
    section: 'voice',
  },
  {
    key: 'sttEnabled',
    formKey: 'sttEnabled',
    configPath: 'stt.enabled',
    label: 'STT',
    kind: 'checkbox',
    defaultValue: true,
    section: 'voice',
  },
  {
    key: 'requireMention',
    formKey: 'requireMention',
    configPath: 'requireMention',
    label: 'Require Mention',
    kind: 'checkbox',
    defaultValue: false,
    section: 'policy',
  },
  {
    key: 'dmAllowlist',
    formKey: 'dmAllowlist',
    configPath: 'dmAllowlist',
    label: 'DM Allowlist',
    kind: 'textarea',
    placeholder: '+15551234567\n15551234567@s.whatsapp.net',
    helperText: 'Phone numbers are accepted; include country code when known.',
    section: 'policy',
  },
  {
    key: 'groupAllowlist',
    formKey: 'groupAllowlist',
    configPath: 'groupAllowlist',
    label: 'Group Allowlist',
    kind: 'textarea',
    placeholder: '120363012345@g.us',
    helperText: 'Groups require the WhatsApp group id ending in @g.us.',
    section: 'policy',
  },
  {
    key: 'globalAllowlist',
    formKey: 'globalAllowlist',
    configPath: 'globalAllowlist',
    label: 'Global Allowlist',
    kind: 'textarea',
    placeholder: '+15551234567\n120363012345@g.us',
    helperText: 'Applies to both direct messages and groups.',
    section: 'policy',
  },
]

const GOOGLECHAT_FIELDS: readonly ChannelDescriptorField[] = [
  {
    key: 'accountId',
    formKey: 'accountId',
    label: 'Account ID',
    kind: 'text',
    required: true,
    placeholder: 'google-chat-main',
    section: 'identity',
  },
  {
    key: 'displayName',
    formKey: 'displayName',
    label: 'Display Name',
    kind: 'text',
    required: true,
    placeholder: 'Google Chat',
    section: 'identity',
  },
  {
    key: 'serviceAccountJson',
    formKey: 'serviceAccountJson',
    label: 'Service Account JSON',
    kind: 'textarea',
    required: true,
    secret: true,
    placeholder: '{"client_email":"...","private_key":"..."}',
    helperText: 'Stored encrypted in the commander secret vault.',
    section: 'credentials',
  },
  {
    key: 'webhookAudience',
    formKey: 'webhookAudience',
    configPath: 'webhookAudience',
    label: 'Webhook Audience',
    kind: 'text',
    required: true,
    placeholder: 'https://example.com/api/commanders/channels/googlechat/events',
    section: 'webhook',
  },
  {
    key: 'webhookAudienceType',
    formKey: 'webhookAudienceType',
    configPath: 'webhookAudienceType',
    label: 'Audience Type',
    kind: 'select',
    required: true,
    defaultValue: 'url',
    section: 'webhook',
    options: [
      { value: 'url', label: 'Endpoint URL' },
      { value: 'project-number', label: 'Project Number' },
    ],
  },
  {
    key: 'projectId',
    formKey: 'projectId',
    configPath: 'projectId',
    label: 'Project ID',
    kind: 'text',
    placeholder: 'my-chat-app',
    section: 'app',
  },
  {
    key: 'projectNumber',
    formKey: 'projectNumber',
    configPath: 'projectNumber',
    label: 'Project Number',
    kind: 'text',
    placeholder: '1234567890',
    section: 'app',
  },
  {
    key: 'botUserName',
    formKey: 'botUserName',
    configPath: 'botUserName',
    label: 'Bot User',
    kind: 'text',
    placeholder: 'users/123456789',
    helperText: 'Optional; used to enforce @mention matching in spaces.',
    section: 'app',
  },
  {
    key: 'defaultCommanderId',
    formKey: 'defaultCommanderId',
    label: 'Default Commander',
    kind: 'select',
    section: 'binding',
  },
  {
    key: 'dmPolicy',
    formKey: 'dmPolicy',
    configPath: 'dmPolicy',
    label: 'DM Policy',
    kind: 'select',
    defaultValue: 'allowlist',
    section: 'policy',
    options: POLICY_OPTIONS,
  },
  {
    key: 'groupPolicy',
    formKey: 'groupPolicy',
    configPath: 'groupPolicy',
    label: 'Space Policy',
    kind: 'select',
    defaultValue: 'disabled',
    section: 'policy',
    options: POLICY_OPTIONS,
  },
  {
    key: 'requireMention',
    formKey: 'requireMention',
    configPath: 'requireMention',
    label: 'Require Mention',
    kind: 'checkbox',
    defaultValue: true,
    section: 'policy',
  },
  {
    key: 'dmAllowlist',
    formKey: 'dmAllowlist',
    configPath: 'dmAllowlist',
    label: 'DM Allowlist',
    kind: 'textarea',
    placeholder: 'users/123456789\nperson@example.com',
    helperText: 'Direct senders may be matched by Chat user id or email when present.',
    section: 'policy',
  },
  {
    key: 'groupAllowlist',
    formKey: 'groupAllowlist',
    configPath: 'groupAllowlist',
    label: 'Space Allowlist',
    kind: 'textarea',
    placeholder: 'spaces/AAAA...',
    helperText: 'Spaces and group chats use the Google Chat space resource name.',
    section: 'policy',
  },
  {
    key: 'globalAllowlist',
    formKey: 'globalAllowlist',
    configPath: 'globalAllowlist',
    label: 'Global Allowlist',
    kind: 'textarea',
    placeholder: 'users/123456789\nspaces/AAAA...',
    section: 'policy',
  },
  {
    key: 'maxMessageBytes',
    formKey: 'maxMessageBytes',
    configPath: 'maxMessageBytes',
    label: 'Message Bytes',
    kind: 'number',
    required: true,
    min: 1024,
    defaultValue: '30000',
    helperText: 'Google Chat message payloads must stay below 32,000 bytes.',
    section: 'outbound',
  },
]

const GENERIC_DESCRIPTOR_FIELDS: readonly ChannelDescriptorField[] = [
  {
    key: 'accountId',
    formKey: 'accountId',
    label: 'Account ID',
    kind: 'text',
    required: true,
    placeholder: 'account-main',
    section: 'identity',
  },
  {
    key: 'displayName',
    formKey: 'displayName',
    label: 'Display Name',
    kind: 'text',
    required: true,
    placeholder: 'Main Channel',
    section: 'identity',
  },
]

export const EMAIL_CHANNEL_FORM_DEFAULTS = {
  accountId: '',
  displayName: '',
  username: '',
  fromAddress: '',
  replyFromAddress: '',
  emailAlias: '',
  defaultCommanderId: '',
  appPassword: '',
  imapHost: 'imap.gmail.com',
  imapPort: '993',
  imapSecure: true,
  imapMailbox: 'INBOX',
  smtpHost: 'smtp.gmail.com',
  smtpPort: '465',
  smtpSecure: true,
  pollIntervalSeconds: '15',
  allowlist: '',
  globalAllowlist: '',
} as const

export const EMAIL_CHANNEL_CONFIG_DEFAULTS = {
  provider: 'email',
  imapHost: 'imap.gmail.com',
  imapPort: 993,
  imapSecure: true,
  imapMailbox: 'INBOX',
  smtpHost: 'smtp.gmail.com',
  smtpPort: 465,
  smtpSecure: true,
  pollIntervalMs: 15_000,
  allowlist: [],
  globalAllowlist: [],
  dmPolicy: 'allowlist',
  groupPolicy: 'disabled',
} as const

export const WHATSAPP_CHANNEL_FORM_DEFAULTS = {
  accountId: '',
  displayName: '',
  transport: 'baileys',
  browserName: 'Hervald',
  authStateDir: '',
  connectTimeoutSeconds: '30',
  printQrInTerminal: true,
  markOnlineOnConnect: false,
  syncFullHistory: false,
  reconnect: true,
  sendTextWithVoiceNote: false,
  dmPolicy: 'allowlist',
  groupPolicy: 'disabled',
  dmAllowlist: '',
  groupAllowlist: '',
  globalAllowlist: '',
  requireMention: false,
  ttsEnabled: false,
  ttsVoice: 'alloy',
  sttEnabled: true,
} as const

export const WHATSAPP_CHANNEL_CONFIG_DEFAULTS = {
  provider: 'whatsapp',
  transport: 'baileys',
  baileys: {
    browserName: 'Hervald',
    connectTimeoutMs: 30_000,
    printQrInTerminal: true,
    markOnlineOnConnect: false,
    syncFullHistory: false,
    reconnect: true,
    sendTextWithVoiceNote: false,
  },
  dmPolicy: 'allowlist',
  groupPolicy: 'disabled',
  dmAllowlist: [],
  groupAllowlist: [],
  allowlist: [],
  globalAllowlist: [],
  requireMention: false,
  tts: {
    enabled: false,
    voice: 'alloy',
  },
  stt: {
    enabled: true,
  },
} as const

export const GOOGLECHAT_CHANNEL_FORM_DEFAULTS = {
  accountId: '',
  displayName: '',
  serviceAccountJson: '',
  webhookAudience: '',
  webhookAudienceType: 'url',
  projectId: '',
  projectNumber: '',
  botUserName: '',
  defaultCommanderId: '',
  dmPolicy: 'allowlist',
  groupPolicy: 'disabled',
  dmAllowlist: '',
  groupAllowlist: '',
  globalAllowlist: '',
  requireMention: true,
  maxMessageBytes: '30000',
} as const

export const GOOGLECHAT_CHANNEL_CONFIG_DEFAULTS = {
  provider: 'googlechat',
  webhookAudience: '',
  webhookAudienceType: 'url',
  dmPolicy: 'allowlist',
  groupPolicy: 'disabled',
  dmAllowlist: [],
  groupAllowlist: [],
  allowlist: [],
  globalAllowlist: [],
  requireMention: true,
  maxMessageBytes: 30_000,
} as const

const CHANNEL_PROVIDER_DESCRIPTORS: readonly ChannelProviderDescriptor[] = [
  {
    provider: 'email',
    label: PROVIDER_LABELS.email,
    fields: [...EMAIL_FIELDS],
    configDefaults: EMAIL_CHANNEL_CONFIG_DEFAULTS,
    formDefaults: EMAIL_CHANNEL_FORM_DEFAULTS,
    credentialFields: ['appPassword'],
    policyFields: ['allowlist', 'globalAllowlist'],
    pairing: { mode: 'none' },
    commanderBinding: COMMANDER_BINDING,
  },
  {
    provider: 'whatsapp',
    label: PROVIDER_LABELS.whatsapp,
    fields: [...WHATSAPP_FIELDS],
    configDefaults: WHATSAPP_CHANNEL_CONFIG_DEFAULTS,
    formDefaults: WHATSAPP_CHANNEL_FORM_DEFAULTS,
    credentialFields: [],
    policyFields: ['dmPolicy', 'groupPolicy', 'dmAllowlist', 'groupAllowlist', 'globalAllowlist', 'requireMention'],
    pairing: { mode: 'qr', transport: 'baileys', statusPollIntervalMs: 2_000 },
    commanderBinding: COMMANDER_BINDING,
  },
  {
    provider: 'googlechat',
    label: PROVIDER_LABELS.googlechat,
    fields: [...GOOGLECHAT_FIELDS],
    configDefaults: GOOGLECHAT_CHANNEL_CONFIG_DEFAULTS,
    formDefaults: GOOGLECHAT_CHANNEL_FORM_DEFAULTS,
    credentialFields: ['serviceAccountJson'],
    policyFields: ['dmPolicy', 'groupPolicy', 'dmAllowlist', 'groupAllowlist', 'globalAllowlist', 'requireMention'],
    pairing: { mode: 'none' },
    commanderBinding: COMMANDER_BINDING,
  },
  {
    provider: 'telegram',
    label: PROVIDER_LABELS.telegram,
    fields: [...GENERIC_DESCRIPTOR_FIELDS],
    configDefaults: {},
    formDefaults: { accountId: '', displayName: '' },
    credentialFields: [],
    policyFields: [],
    pairing: { mode: 'none' },
    commanderBinding: COMMANDER_BINDING,
  },
  {
    provider: 'discord',
    label: PROVIDER_LABELS.discord,
    fields: [...GENERIC_DESCRIPTOR_FIELDS],
    configDefaults: {},
    formDefaults: { accountId: '', displayName: '' },
    credentialFields: [],
    policyFields: [],
    pairing: { mode: 'none' },
    commanderBinding: COMMANDER_BINDING,
  },
]

function cloneDescriptor(descriptor: ChannelProviderDescriptor): ChannelProviderDescriptor {
  return {
    ...descriptor,
    fields: descriptor.fields.map((field) => ({
      ...field,
      ...(field.options ? { options: field.options.map((option) => ({ ...option })) } : {}),
    })),
    configDefaults: structuredClone(descriptor.configDefaults),
    formDefaults: { ...descriptor.formDefaults },
    credentialFields: [...descriptor.credentialFields],
    policyFields: [...descriptor.policyFields],
    pairing: { ...descriptor.pairing },
    commanderBinding: { ...descriptor.commanderBinding },
    ...(descriptor.bindingState ? { bindingState: { ...descriptor.bindingState } } : {}),
  }
}

function trimString(value: unknown): string | undefined {
  const normalized = typeof value === 'string' ? value.trim() : ''
  return normalized.length > 0 ? normalized : undefined
}

export function getChannelProviderDescriptor(provider: ChannelProvider): ChannelProviderDescriptor | null {
  const descriptor = CHANNEL_PROVIDER_DESCRIPTORS.find((entry) => entry.provider === provider)
  return descriptor ? cloneDescriptor(descriptor) : null
}

export function listChannelProviderDescriptors(input: {
  commanderId?: string
  bindings?: readonly CommanderChannelBinding[]
} = {}): ChannelProviderDescriptor[] {
  return CHANNEL_PROVIDER_DESCRIPTORS.map((descriptor) => {
    const projected = cloneDescriptor(descriptor)
    if (input.commanderId) {
      projected.bindingState = {
        defaultCommanderId: input.commanderId,
        effectiveCommanderId: input.commanderId,
        source: 'binding-owner',
      }
    }
    const binding = input.bindings?.find((candidate) => candidate.provider === descriptor.provider)
    if (binding) {
      projected.bindingState = projectChannelBindingState(binding)
    }
    return projected
  })
}

export function projectChannelBindingState(binding: CommanderChannelBinding): ChannelCommanderBindingState {
  const defaultCommanderId =
    trimString(binding.config.defaultCommanderId)
    ?? binding.commanderId
  return {
    defaultCommanderId,
    effectiveCommanderId: defaultCommanderId,
    source: trimString(binding.config.defaultCommanderId)
        ? 'legacy-provider-config'
        : 'binding-owner',
  }
}
