const DEFAULT_HEARTBEAT_MESSAGE = 'Check for pending tasks and report status.'
const MS_PER_MINUTE = 60_000

export interface CommanderMdPreviewProps {
  host: string
  displayName?: string
  cwd?: string
  persona?: string
  agentType?: 'claude' | 'codex' | 'gemini'
  effort?: 'low' | 'medium' | 'high' | 'max'
  heartbeatIntervalMs?: number
  heartbeatMessage?: string
  fatPinInterval?: number
  taskSource?: {
    owner: string
    repo: string
    label?: string
    project?: string
  }
}

/**
 * Returns a YAML-safe scalar representation of a string value.
 * For preview purposes, wraps values containing special YAML characters in double quotes.
 * Empty/absent values render as `~` (YAML null).
 */
function toYamlScalar(value: string | undefined): string {
  if (!value || value.trim() === '') {
    return '~'
  }
  // Characters that require quoting in YAML plain scalars
  const needsQuotes = /[:#\[\]{}&*!|>'"%@`,\n\r]/.test(value) || value.trim() !== value
  if (needsQuotes) {
    return `"${value.replaceAll('"', '\\"')}"`
  }
  return value
}

function formatHeartbeatInterval(intervalMs: number | undefined): string {
  if (intervalMs == null || !Number.isFinite(intervalMs) || intervalMs <= 0) {
    return '15 minutes'
  }
  if (intervalMs < MS_PER_MINUTE) {
    return `${intervalMs} ms`
  }
  const minutes = Math.round(intervalMs / MS_PER_MINUTE)
  return minutes === 1 ? '1 minute' : `${minutes} minutes`
}

function buildPreviewContent(props: CommanderMdPreviewProps): string {
  const {
    host,
    cwd,
    persona,
    agentType,
    effort,
    heartbeatIntervalMs,
    heartbeatMessage,
    fatPinInterval,
    taskSource,
  } = props

  const idPlaceholder = '<auto-generated>'
  const createdPlaceholder = new Date().toISOString()
  const cwdDisplay = cwd && cwd.trim() !== '' ? cwd.trim() : '(none)'

  const personaValue = persona?.trim() ?? ''
  const hostValue = host.trim()

  const lines: string[] = [
    '---',
    `id: ${toYamlScalar(idPlaceholder)}`,
    `host: ${toYamlScalar(hostValue || undefined)}`,
    `persona: ${toYamlScalar(personaValue || undefined)}`,
    `created: ${toYamlScalar(createdPlaceholder)}`,
    `cwd: ${toYamlScalar(cwd?.trim() || undefined)}`,
    '---',
    '',
    '# Commander Identity',
    '',
    '## Persona',
    personaValue !== '' ? personaValue : '(none)',
    '',
    '## Hostname',
    hostValue !== '' ? hostValue : '(none)',
    '',
    '## Metadata',
    `- Commander ID: \`${idPlaceholder}\``,
    `- Created: \`${createdPlaceholder}\``,
    `- Workspace CWD: ${cwdDisplay}`,
  ]

  if (agentType) {
    lines.push(`- Agent: ${agentType}`)
  }
  if (effort) {
    lines.push(`- Claude effort: ${effort}`)
  }

  // Heartbeat section
  lines.push('')
  lines.push('## Heartbeat')
  lines.push(`- Interval: ${formatHeartbeatInterval(heartbeatIntervalMs)}`)

  const resolvedMessage =
    heartbeatMessage && heartbeatMessage.trim() !== ''
      ? heartbeatMessage.trim()
      : DEFAULT_HEARTBEAT_MESSAGE
  lines.push(`- Message: ${resolvedMessage}`)

  if (fatPinInterval != null && Number.isFinite(fatPinInterval) && fatPinInterval > 0) {
    lines.push(`- Context mode: fat (every ${fatPinInterval} heartbeats)`)
  } else {
    lines.push('- Context mode: thin')
  }

  // Task source section
  if (taskSource && taskSource.owner.trim() !== '' && taskSource.repo.trim() !== '') {
    lines.push('')
    lines.push('## Task Source')
    lines.push(`- GitHub: ${taskSource.owner.trim()}/${taskSource.repo.trim()}`)
    if (taskSource.label && taskSource.label.trim() !== '') {
      lines.push(`- Label filter: ${taskSource.label.trim()}`)
    }
    if (taskSource.project && taskSource.project.trim() !== '') {
      lines.push(`- Project: ${taskSource.project.trim()}`)
    }
  }

  return lines.join('\n')
}

export function CommanderMdPreview(props: CommanderMdPreviewProps): JSX.Element {
  const content = buildPreviewContent(props)

  return (
    <div className="rounded-lg border border-ink-border bg-washi-white overflow-hidden">
      <div className="px-3 py-2 border-b border-ink-border bg-washi-aged/60">
        <span className="text-whisper uppercase tracking-wide text-sumi-diluted">
          Commander configuration preview
        </span>
      </div>
      <pre className="text-xs font-mono text-sumi-gray leading-relaxed overflow-auto max-h-[400px] p-3 whitespace-pre-wrap break-words">
        {content}
      </pre>
    </div>
  )
}
